# Generated by Django 3.2.15 on 2022-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledPupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('school_roll_no', models.CharField(max_length=200)),
            ],
        ),
    ]
