# Generated by Django 3.2.15 on 2022-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledpupil',
            name='pupil_name',
        ),
        migrations.AddField(
            model_name='enrolledpupil',
            name='pupil_first_name',
            field=models.CharField(default='First Name', max_length=200),
        ),
        migrations.AddField(
            model_name='enrolledpupil',
            name='pupil_last_name',
            field=models.CharField(default='Last Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_name',
            field=models.CharField(default='School Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_roll_no',
            field=models.CharField(default='Roll Number', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='teacher_name',
            field=models.CharField(default='Teacher Name', max_length=200),
        ),
    ]
