# Generated by Django 3.2.15 on 2022-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0002_auto_20220924_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_roll_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='teacher_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
