# Generated by Django 3.2.15 on 2022-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0003_auto_20220924_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.IntegerField(default=''),
        ),
    ]
