# Generated by Django 3.2.15 on 2022-09-24 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0005_alter_enrolledpupil_pupil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
