# Generated by Django 3.2.15 on 2022-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0006_alter_enrolledpupil_pupil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
