# Generated by Django 3.2.15 on 2022-09-26 21:24

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0010_alter_enrolledpupil_pupil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('my_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_one_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_one_number', models.PositiveIntegerField(default=0)),
                ('my_emergency_contact_two_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_two_number', models.PositiveIntegerField(default=0)),
                ('my_date_of_birth', models.DateField(default='DD/MM/YY')),
                ('my_biography', models.TextField(max_length=600)),
                ('my_family', models.TextField(max_length=600)),
                ('my_likes', models.TextField(max_length=600)),
                ('my_dislikes', models.TextField(max_length=600)),
                ('my_strengths', models.TextField(max_length=600)),
                ('my_difficulties', models.TextField(max_length=600)),
                ('my_supports', models.TextField(max_length=600)),
                ('my_calming_measures', models.TextField(max_length=600)),
                ('my_communication_skills', models.TextField(max_length=600)),
                ('my_other_info', models.TextField(max_length=600)),
                ('my_family_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
