# Generated by Django 3.2.15 on 2022-09-26 21:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PASSPORT', '0011_auto_20220926_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='my_additional_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_hobby_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
